// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGLApp.Infrastructure.Context;

#nullable disable

namespace SGLApp.Infrastructure.Migrations
{
    [DbContext(typeof(SGLAppDbContext))]
    partial class SGLAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SGLApp.Domain.Entities.Credit", b =>
                {
                    b.Property<int>("Auto_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Auto_Id"));

                    b.Property<int?>("AgentNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BankBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transaction_reference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Auto_Id");

                    b.ToTable("CreditTransmissions");
                });

            modelBuilder.Entity("SGLApp.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("RealTimeTicket_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RealTimeTicket_Id"));

                    b.Property<bool?>("Canceled")
                        .HasColumnType("bit");

                    b.Property<decimal?>("DirectAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DirectBet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DrawDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DrawNo")
                        .HasColumnType("int");

                    b.Property<string>("EncryptedData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullTicket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMEI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("POSBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("POSDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("POSID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PermAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PermBet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNetwork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RetailerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SalesDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SalesSynced")
                        .HasColumnType("int");

                    b.Property<string>("TicketNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RealTimeTicket_Id");

                    b.ToTable("RealTimeTickets");
                });

            modelBuilder.Entity("SGLApp.Domain.Entities.WinningTicket", b =>
                {
                    b.Property<int>("WinningTicket_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WinningTicket_Id"));

                    b.Property<int>("Agent_code")
                        .HasColumnType("int");

                    b.Property<decimal?>("Payout")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Sale")
                        .HasColumnType("datetime2");

                    b.Property<int>("Terminal_Sale")
                        .HasColumnType("int");

                    b.Property<string>("Ticket_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticket_Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticket_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Upload")
                        .HasColumnType("datetime2");

                    b.HasKey("WinningTicket_Id");

                    b.ToTable("WinningTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
